SQL_PASSWORD = "YOURKEYHERE"
SQL_PUBLIC_IP = "YOURKEYHERE"
SQL_DATABASE_NAME = "YOURKEYHERE"
BUCKET_NAME = "YOURKEYHERE"
SECRET_KEY = "YOURKEYHERE"

# AutoML
PROJECT_ID = "YOURKEYHERE"
MODEL_ID = "YOURKEYHERE"